### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by gosymbian** [MobMaxime/xamarin-android-samples#1]
Hi,

I'm getting the following error while compiling :

Error   1   Unsupported or invalid $(TargetFrameworkVersion) value of 'v3.1'. Please update your Project Options.   C:\DISK_C\Android\Appli_xamarin\MobMaxime\xamarin-android-samples\SamplePopover\PopOver\PopOver.csproj PopOver

I'm using VS2012 and have installed the starter version of xamarin yesterday therefore, it's the last version !

PS: are you french ?

any idea ?
thanks in advance for your help and sharing code,
sincerly,
Domi.

**Comment by Harshadcse** [comment]
@ Domi

Please changes manifest 
**Minimum Android version** and **Target Android version**  API 15 Above.
